### ISSUE TITLE
Issues with some clubs

### ISSUE THREAD

**Issue by FranGoitia** [openfootball/build-shell#1]
Hello. There are some issues with clubs that are named similarly. For example, even though Arsenal from England and Arsenal de Sarandi from Argentina have different ids in the clubs table, the games tables associates both matches from Arsenal de Sarandi and Arsenal de Inglaterra with the id that corresponds to Arsenal de Sarandi.

**Comment by geraldb** [comment]
Thanks for reporting. Please post the issue(s) about the clubs to the [mailing list / forum](http://group.google.com/group/opensport). Nobody follows along the issues here. Thanks. Cheers.
